image: awhalen/docker-php-composer-node

stages:
  - deploy

deploy_staging:
  stage: deploy
  script:
    - echo "Deploying to staging."
    - ls
    - npm install
    - composer install
    - ls
  environment:
    name: staging
    url: https://systemmanager.genericdevelopment.nl
  only:
    - master

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production."
  environment:
    name: production
    url: https://systemmanager.io
  when: manual
  only:
    - master
