before_script:
  - echo $CI_JOB_STAGE
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 700 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - ssh-keyscan -H 'nl-ams1-01.genericdevelopment.nl' >> ~/.ssh/known_hosts

image: awhalen/docker-php-composer-node

cache:
  key: "SystemManager-Showcase-Staging"
  paths:
    - "node_modules/"
    - "vendor/"


stages:
  - build
  - test
  - staging
  - production

build:
  stage: build
  script:
    - npm install
    - composer install
    - npm run production
  artifacts:
    paths:
      - './'

test:
  stage: test
  script:
    - echo "No tests are defined yet"

deploy_staging:
  stage: staging
  script:
    - echo "Deploying to staging."
    - rsync -airzP "$PWD"/* root@nl-ams1-01.genericdevelopment.nl:/var/www/systemmanager_showcase/
  environment:
    name: staging
    url: https://systemmanager.genericdevelopment.nl
  only:
    - master
  artifacts:
    paths:
      - './'

deploy_prod:
  stage: production
  script:
    - echo "Deploy to production."
  environment:
    name: production
    url: https://systemmanager.io
  when: manual
  only:
    - master
