before_script:
  - echo $CI_JOB_STAGE
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 700 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - ssh-keyscan -H 'nl-ams1-01.genericdevelopment.nl' >> ~/.ssh/known_hosts

image: awhalen/docker-php-composer-node

stages:
  - deploy

deploy_staging:
  stage: deploy
  script:
    - echo "Deploying to staging."
    - ls
    - npm install
    - composer install
    - npm run production
    - ls
    - rsync -a / root@nl-ams1-01.genericdevelopment.nl:/var/www/systemmanager_showcase
  environment:
    name: staging
    url: https://systemmanager.genericdevelopment.nl
  only:
    - master

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production."
  environment:
    name: production
    url: https://systemmanager.io
  when: manual
  only:
    - master
